In [1]:
#pip install wikipedia

In [2]:
import requests
from bs4 import BeautifulSoup
import random
def scrapeURLs(url):
    listOfLinks = []
    response = requests.get(
        url=url,
    )
    soup = BeautifulSoup(response.content, 'html.parser')

    title = soup.find(id="firstHeading")

    # Get all the links
    allLinks = soup.find(id="bodyContent").find_all("a")
    linkToScrape = 0

    for link in allLinks:
        # We are only interested in other wiki articles
        if link['href'].find("/wiki/") == -1: 
            continue

        linkToScrape = link
        listOfLinks.append(str("https://en.wikipedia.org"+linkToScrape['href']))
    return(listOfLinks)

In [3]:
listOfLinksToScrape = scrapeURLs("https://en.wikipedia.org/wiki/List_of_tourist_attractions_in_Denmark#Top_50_most_visited_attractions_in_Denmark")

In [4]:
bad_names = ['Tourism_in_Denmark',
'Roskilde',
'Aalborg',
'Carlsberg_Group',
'Lolland',
'VisitDenmark',
'Tourist_attraction',
'Denmark']

In [5]:
from urllib.parse import unquote
names = []
for link in listOfLinksToScrape:
    x = str(link.split('/')[-1])
    x = unquote(x)
    if "&" in x or "Category" in x or "List" in x or x in bad_names:
        print("Bad site: " + x)
    else:
        names.append(x)
names = list(set(names))
len(names)

Bad site: Tourist_attraction
Bad site: Denmark
Bad site: VisitDenmark
Bad site: List_of_national_parks_of_Denmark
Bad site: Lolland
Bad site: Aalborg
Bad site: Post_&_Tele_Museum
Bad site: Lolland
Bad site: Carlsberg_Group
Bad site: Aalborg
Bad site: Roskilde
Bad site: Tourism_in_Denmark
Bad site: List_of_museums_in_Denmark
Bad site: Help:Category
Bad site: Category:Tourism_in_Denmark
Bad site: Category:Tourist_attractions_in_Denmark
Bad site: Category:Lists_of_tourist_attractions_in_Denmark
Bad site: Category:CS1_Danish-language_sources_(da)
Bad site: Category:Articles_with_short_description
Bad site: Category:Short_description_is_different_from_Wikidata

50

In [6]:
manual_categories = {'Egeskov_Castle':'Castle',
                  'Royal_Danish_Theatre':'Theatre',
                  'Djurs_Sommerland':'Amusement Park',
                  'Arken_Museum_of_Modern_Art':'Museum',
                  'Rundetårn':'History',
                  'Tivoli_Gardens':'Park',
                  'Odense_Zoo':'Zoo',
                  'BonBon-Land':'Amusement Park',
                  'Copenhagen_Concert_Hall':'Theatre',
                  'Givskud_Zoo':'Zoo',
                  'Ree_Park_–_Ebeltoft_Safari':'Zoo',
                  'National_Aquarium_Denmark':'Aquarium',
                  'Christiansborg':'Castle',
                  'Danish_Film_Institute':['Museum','Theatre'],
                  'Copenhagen_Zoo':'Zoo',
                    'Statens_Museum_for_Kunst':'Museum',
                     'Ny_Carlsberg_Glyptotek':'Museum',
                     'Kronborg_Castle':'Castle',
                     'Natural_History_Museum_of_Denmark':'Museum',
                     'Fårup_Sommerland':'Amusement Park',
                     'Tivoli_Friheden':'Amusement Park',
                     'Copenhagen_Opera_House':'Theatre',
                     'Dyrehavsbakken':'Amusement Park',
                     'Grenen':'Nature',
                     'Legoland_Billund':'Amusement Park',
                     'Viking_Ship_Museum_(Roskilde)':'Museum',
                     'Møns_Klint':'Nature',
                     'Jægersborg_Dyrehave':'Park',
                     'Freetown_Christiania':'History',
                     'Jesperhus':['Resort','Park'],
                     'Rosenborg_Castle':'Castle',
                     'Knuthenborg_Safari_Park':['Zoo','Park'],
                     'Royal_Danish_Playhouse':'Theatre',
                     'ARoS_Aarhus_Kunstmuseum':'Museum',
                     'Nordsøen_Oceanarium':'Aquarium',
                     'Skagen_Odde':'Nature',
                     'Tycho_Brahe_Planetarium':'Museum',
                     'Lalandia':'Amusement Park',
                     'Fisheries_and_Maritime_Museum,_Esbjerg':['Aquarium','Museum'],
                     'Frederiksborg_Palace':['Castle','Museum','History'],
                     'Frilandsmuseet':'Museum',
                     'National_Museum_of_Denmark':'Museum',
                     'The_Little_Mermaid':'History',
                     'Utzon_Center':['Museum','Centre'],
                     'Aalborg_Zoo':'Zoo',
                     'Bella_Centre':'Centre',
                     'Den_Gamle_By':'History',
                     'Kattegatcentret':'Centre',
                     'Randers_Tropical_Zoo':'Zoo',
                     'Louisiana_Museum_of_Modern_Art':'Museum'
                    }

In [7]:
manual_prices = {'Egeskov_Castle':'0',
                  'Royal_Danish_Theatre':'0',
                  'Djurs_Sommerland':'3',
                  'Arken_Museum_of_Modern_Art':'1',
                  'Rundetårn':'1',
                  'Tivoli_Gardens':'1',
                  'Odense_Zoo':'2',
                  'BonBon-Land':'3',
                  'Copenhagen_Concert_Hall':'2',
                  'Givskud_Zoo':'3',
                  'Ree_Park_–_Ebeltoft_Safari':'3',
                  'National_Aquarium_Denmark':'1',
                  'Christiansborg':'0',
                  'Danish_Film_Institute':'0',
                  'Copenhagen_Zoo':'2',
                    'Statens_Museum_for_Kunst':'1',
                     'Ny_Carlsberg_Glyptotek':'1',
                     'Kronborg_Castle':'0',
                     'Natural_History_Museum_of_Denmark':'1',
                     'Fårup_Sommerland':'3',
                     'Tivoli_Friheden':'2',
                     'Copenhagen_Opera_House':'1',
                     'Dyrehavsbakken':'0',
                     'Grenen':'0',
                     'Legoland_Billund':'4',
                     'Viking_Ship_Museum_(Roskilde)':'2',
                     'Møns_Klint':'0',
                     'Jægersborg_Dyrehave':'0',
                     'Freetown_Christiania':'0',
                     'Jesperhus':'2',
                     'Rosenborg_Castle':'0',
                     'Knuthenborg_Safari_Park':'2',
                     'Royal_Danish_Playhouse':'1',
                     'ARoS_Aarhus_Kunstmuseum':'2',
                     'Nordsøen_Oceanarium':'3',
                     'Skagen_Odde':'0',
                     'Tycho_Brahe_Planetarium':'1',
                     'Lalandia':'4',
                     'Fisheries_and_Maritime_Museum,_Esbjerg':'2',
                     'Frederiksborg_Palace':'1',
                     'Frilandsmuseet':'1',
                     'National_Museum_of_Denmark':'1',
                     'The_Little_Mermaid':'0',
                     'Utzon_Center':'1',
                     'Aalborg_Zoo':'3',
                     'Bella_Centre':'0',
                     'Den_Gamle_By':'1',
                     'Kattegatcentret':'0',
                     'Randers_Tropical_Zoo':'4',
                     'Louisiana_Museum_of_Modern_Art':'2'
                    }

In [8]:
def scrapeInfo(url):
    listOfLinks = []
    response = requests.get(
        url=url,
    )
    soup = BeautifulSoup(response.content, 'html.parser')
    title = soup.find(id="firstHeading")
    allLinks = soup.find(id="bodyContent").find_all("a")
    linkToScrape = 0

    for link in allLinks:
        # We are only interested in other wiki articles
        if link['href'].find("/wiki/") == -1: 
            continue

        linkToScrape = link
        listOfLinks.append(str("https://en.wikipedia.org"+linkToScrape['href']))
    return(listOfLinks)

In [9]:
def conversion(old):
    direction = {'N':1, 'S':-1, 'E': 1, 'W':-1}
    new = old.replace(u'°',' ').replace('′',' ').replace('″',' ')
    new = new.split()
    new_dir = new.pop()
    new.extend([0,0,0])
    return (int(new[0])+int(new[1])/60.0+int(new[2])/3600.0) * direction[new_dir]

In [10]:
import wikipedia
import pandas as pd
import os
import re

ShortDescription = []
LongDescription = []
latitude_list = []
longitude_list = []
df_adventures = pd.DataFrame()

for name in names:
    sDesc = wikipedia.summary(name, sentences=1)
    sDesc = re.sub('\.(?!\s|\d|$)', '. ', sDesc)
    lDesc = wikipedia.summary(name, sentences=5)
    lDesc = lDesc.replace(';','')
    lDesc = re.sub('== [^>]+ ==', '', lDesc)
    lDesc = os.linesep.join([s for s in lDesc.splitlines() if s])
    lDesc = str.join(" ", lDesc.splitlines())
    print(sDesc + '\n')
    ShortDescription.append(sDesc)
    LongDescription.append(lDesc)

    try:
        req = requests.get("https://en.wikipedia.org/wiki/"+name).text
        soup = BeautifulSoup(req, 'lxml')
        
        latitude_old = soup.find("span", {"class": "latitude"}).text
        longitude_old = soup.find("span", {"class": "longitude"}).text
        latitude_list.append(conversion(latitude_old))
        longitude_list.append(conversion(longitude_old))
    except:
        latitude_list.append('0')
        longitude_list.append('0')
df_adventures['Title'] = names
df_adventures['ShortDescription'] = ShortDescription
df_adventures['LongDescription'] = LongDescription
df_adventures['Category'] = df_adventures.Title.map(manual_categories)
df_adventures['Latitude'] = latitude_list
df_adventures['Longitude'] = longitude_list
df_adventures['Price'] = df_adventures.Title.map(manual_prices)
df_adventures['Picture'] = 0

The ARoS Aarhus Kunstmuseum is an art museum in Aarhus, Denmark.

The Copenhagen Opera House (in Danish usually called Operaen, literally The opera) is the national opera house of Denmark, and among the most modern opera houses in the world.

The Natural History Museum of Denmark (Danish: Statens Naturhistoriske Museum) is a natural history museum located in Copenhagen, Denmark.

The Fisheries and Maritime Museum (Danish: Fiskeri- og Søfartsmuseet) is a privately owned museum in Esbjerg, Denmark.

Ree Park Safari is a safari park in Djursland on the peninsula of Jutland, Denmark.

The Round Tower (Danish: Rundetårn) is a 17th-century tower in Copenhagen, Denmark, one of the many architectural projects of Christian IV of Denmark.

The Viking Ship Museum (Danish: Vikingeskibsmuseet) in Roskilde is Denmark's national ship museum for ships of the prehistoric and medieval period.

Fårup Summer Park (Danish: Fårup Sommerland) is a theme park located in Fårup between Blokhus and Løkken in North Jutland, Denmark.

Tivoli Gardens, also known simply as Tivoli, is an amusement park and pleasure garden in Copenhagen, Denmark.

Dyrehaven (Danish 'The Deer Park'), officially Jægersborg Dyrehave, is a forest park north of Copenhagen.

Randers Tropical Zoo (Danish: Randers Regnskov) is an indoor zoo in Randers, Denmark.

Frilandsmuseet (English: Open Air Museum) is an open-air museum on the northern outskirts of Copenhagen, Denmark.

Freetown Christiania (Danish: Fristaden Christiania), also known as Christiania or simply the Staden, is an intentional community and commune in the Christianshavn neighbourhood of the Danish capital city of Copenhagen.

The Louisiana Museum of Modern Art is an art museum located on the shore of the Øresund Sound in Humlebæk, 35 km (22 mi) north of Copenhagen, Denmark.

Frederiksborg Castle (Danish: Frederiksborg Slot) is a palatial complex in Hillerød, Denmark.

The Utzon Center in Aalborg, Denmark, was the last building to be designed by Jørn Utzon, the architect behind the Sydney Opera House.

Legoland Billund Resort, the original Legoland park, opened on 7 June 1968 in Billund, Denmark.

Egeskov Castle (Danish: Egeskov Slot) is located near Kværndrup, in the south of the island of Funen, Denmark.

Christiansborg Palace (Danish: Christiansborg Slot; pronounced [kʰʁestjænsˈpɒˀ ˈslʌt]) is a palace and government building on the islet of Slotsholmen in central Copenhagen, Denmark.

The National Museum of Denmark (Nationalmuseet) in Copenhagen is Denmark's largest museum of cultural history, comprising the histories of Danish and foreign cultures, alike.

Møns Klint is a 6 km stretch of limestone and chalk cliffs along the eastern coast of the Danish island of Møn in the Baltic Sea.

Grenen is a long sandbar spit at Skagen Odde (the headland of Jutland), north of the town of Skagen.

National Aquarium Denmark, Den Blå Planet (Danish: Den Blå Planet, Danmarks Akvarium) is a public aquarium in Denmark.

BonBon-Land is a Danish amusement park located in Holme-Olstrup in the South of Zealand, about 100 km from Copenhagen.

Copenhagen Zoo (Danish: København Zoo) is a zoological garden in Copenhagen, Denmark.

Djurs Sommerland (English: Djurs Summer Land) is an amusement park located in Djursland, Denmark, just north of the village of Nimtofte, 23 kilometers west of Grenaa, and 36 kilometers east of Randers.

Rosenborg Castle (Danish: Rosenborg Slot) is a renaissance castle located in Copenhagen, Denmark.

The National Gallery of Denmark (Danish: Statens Museum for Kunst, also known as "SMK", literally State Museum for Art) is the Danish national gallery, located in the centre of Copenhagen. The museum collects, registers, maintains, researches and handles Danish and foreign art dating from the 14th century to the present day.

The Royal Danish Playhouse (Danish: Skuespilhuset) is a theatre building for the Royal Danish Theatre, situated on the harbour front in the Frederiksstaden neighbourhood of central Copenhagen, Denmark.

Givskud Zoo is a zoo and safari park in Givskud, 20 kilometres (12 mi) north west of Vejle in Denmark.

"The Little Mermaid" (Danish: Den lille havfrue), sometimes translated in English as "The Little Sea Maid", is a fairy tale written by Danish author Hans Christian Andersen.

Tivoli Friheden is an amusement park located in Aarhus, Denmark.

Dyrehavsbakken  (lit. 'Deer Park Hill'), commonly referred to as Bakken (lit. 'The Hill', to distinguish it from Dyrehaven, a royal deer park with public access) is an amusement park in Lyngby-Taarbæk, Denmark, near Klampenborg and approximately 10 km (6 mi) north of central Copenhagen.

Skagen Odde, also Skagens Odde, sometimes known in English as the Scaw Spit or The Skaw, is a sandy peninsula which stretches some 30 km (19 mi) northeast and comprises the northernmost area of Vendsyssel in Jutland, Denmark. Skagen Odde is reported to be one of the largest spit systems in Europe, created by a continuous process of marine sand and gravel deposition, moved in a north-east direction by longshore currents.

Odense Zoo is a zoological garden in Odense, Denmark.

DR Koncerthuset (Danish pronunciation: [ˈte̝ˀˌɛɐ̯ kʰʌnˈsɛɐ̯tˌhuˀsð̩, - kʰɔnˈ-]), previously known in English as Copenhagen Concert Hall, is a concert hall designed by Jean Nouvel.

Lalandia is the name of three Danish holiday resorts owned by Parken Sport & Entertainment.

Planetarium (formerly Tycho Brahe Planetarium) is located  at the southern end of the lake Skt.

Kattegatcentret (The Kattegat Center) is a public aquarium in Grenå, Denmark.

The Royal Danish Theatre (RDT, Danish: Det Kongelige Teater) is both the national Danish performing arts institution and a name used to refer to its old purpose-built venue from 1874 located on Kongens Nytorv in Copenhagen.

The Ny Carlsberg Glyptotek ("ny" means "new" in Danish; "Glyptotek" comes from the Greek root glyphein, to carve, and theke, storing place), commonly known simply as Glyptoteket, is an art museum in Copenhagen, Denmark.

Bella Center (abbreviated BC) is Scandinavia's second largest exhibition and conference center (after Messecenter Herning), and is located in Copenhagen, Denmark.

Knuthenborg Safaripark is a safari park on the island of Lolland in the southeast of Denmark.

The Danish Film Institute (Danish: Det Danske Filminstitut) is the national Danish agency responsible for supporting and encouraging film and cinema culture, and for conserving these in the national interest.

ARKEN Museum of Modern Art (Danish: ARKEN Museum for Moderne Kunst) is a state-authorised private non-profit charity and contemporary art museum in Ishøj, near Copenhagen.

Jesperhus is a 8-hectare (20-acre) family-owned resort around Legind Bjerge, south of Nykøbing Mors, Denmark.

Nordsøen Oceanarium is a public aquarium and museum that opened in 1998 on the shores of the North Sea in Hirtshals, north Jutland, Denmark.

Den Gamle By, or The Old Town in English, is an open-air town museum located in the Aarhus Botanical Gardens, in central Aarhus, Denmark.

Kronborg is a castle and stronghold in the town of Helsingør, Denmark.

Aalborg Zoo is a zoo located near the center of Aalborg in Denmark.

In [11]:
df_adventures_r = df_adventures[(df_adventures[['Latitude','Longitude']] != '0').all(axis=1)]
df_adventures_r= df_adventures_r.reset_index(drop=True)
df_adventures_r

,Title,ShortDescription,LongDescription,Category,Latitude,Longitude,Price,Picture
0,Copenhagen_Opera_House,The Copenhagen Opera House (in Danish usually ...,The Copenhagen Opera House (in Danish usually ...,Theatre,55.681944,12.600556,1,0
1,Natural_History_Museum_of_Denmark,The Natural History Museum of Denmark (Danish:...,The Natural History Museum of Denmark (Danish:...,Museum,55.6875,12.575556,1,0
2,"Fisheries_and_Maritime_Museum,_Esbjerg",The Fisheries and Maritime Museum (Danish: Fis...,The Fisheries and Maritime Museum (Danish: Fis...,"[Aquarium, Museum]",55.489444,8.411667,2,0
3,Ree_Park_–_Ebeltoft_Safari,Ree Park Safari is a safari park in Djursland ...,Ree Park Safari is a safari park in Djursland ...,Zoo,56.263611,10.736667,3,0
4,Fårup_Sommerland,Fårup Summer Park (Danish: Fårup Sommerland) i...,Fårup Summer Park (Danish: Fårup Sommerland) i...,Amusement Park,57.27,9.645833,3,0
5,Tivoli_Gardens,"Tivoli Gardens, also known simply as Tivoli, i...","Tivoli Gardens, also known simply as Tivoli, i...",Park,55.673611,12.568333,1,0
6,Jægersborg_Dyrehave,"Dyrehaven (Danish 'The Deer Park'), officially...","Dyrehaven (Danish 'The Deer Park'), officially...",Park,55.791389,12.560833,0,0
7,Randers_Tropical_Zoo,Randers Tropical Zoo (Danish: Randers Regnskov...,Randers Tropical Zoo (Danish: Randers Regnskov...,Zoo,56.456944,10.032778,4,0
8,Frilandsmuseet,Frilandsmuseet (English: Open Air Museum) is a...,Frilandsmuseet (English: Open Air Museum) is a...,Museum,55.786111,12.492222,1,0
9,Louisiana_Museum_of_Modern_Art,The Louisiana Museum of Modern Art is an art m...,The Louisiana Museum of Modern Art is an art m...,Museum,55.969444,12.543056,2,0
10,Frederiksborg_Palace,Frederiksborg Castle (Danish: Frederiksborg Sl...,Frederiksborg Castle (Danish: Frederiksborg Sl...,"[Castle, Museum, History]",55.935,12.300833,1,0
11,Utzon_Center,"The Utzon Center in Aalborg, Denmark, was the ...","The Utzon Center in Aalborg, Denmark, was the ...","[Museum, Centre]",57.05,9.924722,1,0
12,Legoland_Billund,"Legoland Billund Resort, the original Legoland...","Legoland Billund Resort, the original Legoland...",Amusement Park,55.735556,9.126111,4,0
13,Egeskov_Castle,Egeskov Castle (Danish: Egeskov Slot) is locat...,Egeskov Castle (Danish: Egeskov Slot) is locat...,Castle,55.176389,10.489444,0,0
14,National_Museum_of_Denmark,The National Museum of Denmark (Nationalmuseet...,The National Museum of Denmark (Nationalmuseet...,Museum,55.674722,12.574722,1,0
15,Møns_Klint,Møns Klint is a 6 km stretch of limestone and ...,Møns Klint is a 6 km stretch of limestone and ...,Nature,54.964167,12.552222,0,0
16,Grenen,Grenen is a long sandbar spit at Skagen Odde (...,Grenen is a long sandbar spit at Skagen Odde (...,Nature,57.743889,10.6475,0,0
17,National_Aquarium_Denmark,"National Aquarium Denmark, Den Blå Planet (Dan...","National Aquarium Denmark, Den Blå Planet (Dan...",Aquarium,55.638056,12.656111,1,0
18,BonBon-Land,BonBon-Land is a Danish amusement park located...,BonBon-Land is a Danish amusement park located...,Amusement Park,55.260556,11.863889,3,0
19,Copenhagen_Zoo,Copenhagen Zoo (Danish: København Zoo) is a zo...,Copenhagen Zoo (Danish: København Zoo) is a zo...,Zoo,55.672778,12.521389,2,0
20,Rosenborg_Castle,Rosenborg Castle (Danish: Rosenborg Slot) is a...,Rosenborg Castle (Danish: Rosenborg Slot) is a...,Castle,55.685556,12.577778,0,0
21,Royal_Danish_Playhouse,The Royal Danish Playhouse (Danish: Skuespilhu...,The Royal Danish Playhouse (Danish: Skuespilhu...,Theatre,55.68,12.594722,1,0
22,Givskud_Zoo,Givskud Zoo is a zoo and safari park in Givsku...,Givskud Zoo is a zoo and safari park in Givsku...,Zoo,55.811667,9.351944,3,0
23,Dyrehavsbakken,"Dyrehavsbakken (lit. 'Deer Park Hill'), commo...","Dyrehavsbakken (lit. 'Deer Park Hill'), commo...",Amusement Park,55.775833,12.574722,0,0
24,Skagen_Odde,"Skagen Odde, also Skagens Odde, sometimes know...","Skagen Odde, also Skagens Odde, sometimes know...",Nature,57.75,10.6,0,0
25,Odense_Zoo,"Odense Zoo is a zoological garden in Odense, D...","Odense Zoo is a zoological garden in Odense, D...",Zoo,55.378056,10.373056,2,0
26,Tycho_Brahe_Planetarium,Planetarium (formerly Tycho Brahe Planetarium)...,Planetarium (formerly Tycho Brahe Planetarium)...,Museum,55.674444,12.558056,1,0
27,Kattegatcentret,Kattegatcentret (The Kattegat Center) is a pub...,Kattegatcentret (The Kattegat Center) is a pub...,Centre,56.406111,10.926667,0,0
28,Ny_Carlsberg_Glyptotek,"The Ny Carlsberg Glyptotek (""ny"" means ""new"" i...","The Ny Carlsberg Glyptotek (""ny"" means ""new"" i...",Museum,55.6725,12.571944,1,0
29,Bella_Centre,Bella Center (abbreviated BC) is Scandinavia's...,Bella Center (abbreviated BC) is Scandinavia's...,Centre,55.6375,12.578333,0,0
30,Knuthenborg_Safari_Park,Knuthenborg Safaripark is a safari park on the...,Knuthenborg Safaripark is a safari park on the...,"[Zoo, Park]",54.823611,11.505833,2,0
31,Arken_Museum_of_Modern_Art,ARKEN Museum of Modern Art (Danish: ARKEN Muse...,ARKEN Museum of Modern Art (Danish: ARKEN Muse...,Museum,55.606111,12.3875,1,0
32,Nordsøen_Oceanarium,Nordsøen Oceanarium is a public aquarium and m...,Nordsøen Oceanarium is a public aquarium and m...,Aquarium,57.586667,9.98,3,0
33,Den_Gamle_By,"Den Gamle By, or The Old Town in English, is a...","Den Gamle By, or The Old Town in English, is a...",History,56.159167,10.190833,1,0
34,Kronborg_Castle,Kronborg is a castle and stronghold in the tow...,Kronborg is a castle and stronghold in the tow...,Castle,56.038889,12.620833,0,0
35,Aalborg_Zoo,Aalborg Zoo is a zoo located near the center o...,Aalborg Zoo is a zoo located near the center o...,Zoo,57.036667,9.898333,3,0

In [12]:
df_adventures_r = df_adventures_r.drop(df_adventures_r[df_adventures_r['Title'] == 'Ny_Carlsberg_Glyptotek'].index)
df_adventures_r= df_adventures_r.reset_index(drop=True)
df_adventures_r

,Title,ShortDescription,LongDescription,Category,Latitude,Longitude,Price,Picture
0,Copenhagen_Opera_House,The Copenhagen Opera House (in Danish usually ...,The Copenhagen Opera House (in Danish usually ...,Theatre,55.681944,12.600556,1,0
1,Natural_History_Museum_of_Denmark,The Natural History Museum of Denmark (Danish:...,The Natural History Museum of Denmark (Danish:...,Museum,55.6875,12.575556,1,0
2,"Fisheries_and_Maritime_Museum,_Esbjerg",The Fisheries and Maritime Museum (Danish: Fis...,The Fisheries and Maritime Museum (Danish: Fis...,"[Aquarium, Museum]",55.489444,8.411667,2,0
3,Ree_Park_–_Ebeltoft_Safari,Ree Park Safari is a safari park in Djursland ...,Ree Park Safari is a safari park in Djursland ...,Zoo,56.263611,10.736667,3,0
4,Fårup_Sommerland,Fårup Summer Park (Danish: Fårup Sommerland) i...,Fårup Summer Park (Danish: Fårup Sommerland) i...,Amusement Park,57.27,9.645833,3,0
5,Tivoli_Gardens,"Tivoli Gardens, also known simply as Tivoli, i...","Tivoli Gardens, also known simply as Tivoli, i...",Park,55.673611,12.568333,1,0
6,Jægersborg_Dyrehave,"Dyrehaven (Danish 'The Deer Park'), officially...","Dyrehaven (Danish 'The Deer Park'), officially...",Park,55.791389,12.560833,0,0
7,Randers_Tropical_Zoo,Randers Tropical Zoo (Danish: Randers Regnskov...,Randers Tropical Zoo (Danish: Randers Regnskov...,Zoo,56.456944,10.032778,4,0
8,Frilandsmuseet,Frilandsmuseet (English: Open Air Museum) is a...,Frilandsmuseet (English: Open Air Museum) is a...,Museum,55.786111,12.492222,1,0
9,Louisiana_Museum_of_Modern_Art,The Louisiana Museum of Modern Art is an art m...,The Louisiana Museum of Modern Art is an art m...,Museum,55.969444,12.543056,2,0
10,Frederiksborg_Palace,Frederiksborg Castle (Danish: Frederiksborg Sl...,Frederiksborg Castle (Danish: Frederiksborg Sl...,"[Castle, Museum, History]",55.935,12.300833,1,0
11,Utzon_Center,"The Utzon Center in Aalborg, Denmark, was the ...","The Utzon Center in Aalborg, Denmark, was the ...","[Museum, Centre]",57.05,9.924722,1,0
12,Legoland_Billund,"Legoland Billund Resort, the original Legoland...","Legoland Billund Resort, the original Legoland...",Amusement Park,55.735556,9.126111,4,0
13,Egeskov_Castle,Egeskov Castle (Danish: Egeskov Slot) is locat...,Egeskov Castle (Danish: Egeskov Slot) is locat...,Castle,55.176389,10.489444,0,0
14,National_Museum_of_Denmark,The National Museum of Denmark (Nationalmuseet...,The National Museum of Denmark (Nationalmuseet...,Museum,55.674722,12.574722,1,0
15,Møns_Klint,Møns Klint is a 6 km stretch of limestone and ...,Møns Klint is a 6 km stretch of limestone and ...,Nature,54.964167,12.552222,0,0
16,Grenen,Grenen is a long sandbar spit at Skagen Odde (...,Grenen is a long sandbar spit at Skagen Odde (...,Nature,57.743889,10.6475,0,0
17,National_Aquarium_Denmark,"National Aquarium Denmark, Den Blå Planet (Dan...","National Aquarium Denmark, Den Blå Planet (Dan...",Aquarium,55.638056,12.656111,1,0
18,BonBon-Land,BonBon-Land is a Danish amusement park located...,BonBon-Land is a Danish amusement park located...,Amusement Park,55.260556,11.863889,3,0
19,Copenhagen_Zoo,Copenhagen Zoo (Danish: København Zoo) is a zo...,Copenhagen Zoo (Danish: København Zoo) is a zo...,Zoo,55.672778,12.521389,2,0
20,Rosenborg_Castle,Rosenborg Castle (Danish: Rosenborg Slot) is a...,Rosenborg Castle (Danish: Rosenborg Slot) is a...,Castle,55.685556,12.577778,0,0
21,Royal_Danish_Playhouse,The Royal Danish Playhouse (Danish: Skuespilhu...,The Royal Danish Playhouse (Danish: Skuespilhu...,Theatre,55.68,12.594722,1,0
22,Givskud_Zoo,Givskud Zoo is a zoo and safari park in Givsku...,Givskud Zoo is a zoo and safari park in Givsku...,Zoo,55.811667,9.351944,3,0
23,Dyrehavsbakken,"Dyrehavsbakken (lit. 'Deer Park Hill'), commo...","Dyrehavsbakken (lit. 'Deer Park Hill'), commo...",Amusement Park,55.775833,12.574722,0,0
24,Skagen_Odde,"Skagen Odde, also Skagens Odde, sometimes know...","Skagen Odde, also Skagens Odde, sometimes know...",Nature,57.75,10.6,0,0
25,Odense_Zoo,"Odense Zoo is a zoological garden in Odense, D...","Odense Zoo is a zoological garden in Odense, D...",Zoo,55.378056,10.373056,2,0
26,Tycho_Brahe_Planetarium,Planetarium (formerly Tycho Brahe Planetarium)...,Planetarium (formerly Tycho Brahe Planetarium)...,Museum,55.674444,12.558056,1,0
27,Kattegatcentret,Kattegatcentret (The Kattegat Center) is a pub...,Kattegatcentret (The Kattegat Center) is a pub...,Centre,56.406111,10.926667,0,0
28,Bella_Centre,Bella Center (abbreviated BC) is Scandinavia's...,Bella Center (abbreviated BC) is Scandinavia's...,Centre,55.6375,12.578333,0,0
29,Knuthenborg_Safari_Park,Knuthenborg Safaripark is a safari park on the...,Knuthenborg Safaripark is a safari park on the...,"[Zoo, Park]",54.823611,11.505833,2,0
30,Arken_Museum_of_Modern_Art,ARKEN Museum of Modern Art (Danish: ARKEN Muse...,ARKEN Museum of Modern Art (Danish: ARKEN Muse...,Museum,55.606111,12.3875,1,0
31,Nordsøen_Oceanarium,Nordsøen Oceanarium is a public aquarium and m...,Nordsøen Oceanarium is a public aquarium and m...,Aquarium,57.586667,9.98,3,0
32,Den_Gamle_By,"Den Gamle By, or The Old Town in English, is a...","Den Gamle By, or The Old Town in English, is a...",History,56.159167,10.190833,1,0
33,Kronborg_Castle,Kronborg is a castle and stronghold in the tow...,Kronborg is a castle and stronghold in the tow...,Castle,56.038889,12.620833,0,0
34,Aalborg_Zoo,Aalborg Zoo is a zoo located near the center o...,Aalborg Zoo is a zoo located near the center o...,Zoo,57.036667,9.898333,3,0

In [13]:
import openpyxl
df_adventures_r.to_csv('attractions_new_11.csv',sep=';',encoding='utf-8-sig', header = None, index = False)

# Sources 
https://en.wikipedia.org/wiki/List_of_tourist_attractions_in_Denmark#Top_50_most_visited_attractions_in_Denmark
https://stackoverflow.com/questions/65162011/how-to-get-coordinates-from-a-wikipedia-page-using-python
https://www.youtube.com/watch?v=8bIsjmfMQxg
https://stackoverflow.com/questions/17193351/how-to-convert-latitude-and-longitude-in-dms-format-into-decimal-format-and-vic